name: Node CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t niskarsha10/nodejsimage -f Dockerfile .
        docker push niskarsha10/nodejsimage
        docker run nodejsimage
