name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env: 
           dockerhub_registry: niskarsha10
           dockerhub_repository: github-image
           image_tag: ${{ github.sha }} 
           USERNAME: ${{ secrets.DOCKER_USERNAME }}
           PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
           
      run: |
             sudo docker login -u $USERNAME -p $PASSWORD
             # docker build . --file Dockerfile --tag dockerimage12
             docker build -t $dockerhub_registry/$dockerhub_repository:$image_tag .
             docker push $dockerhub_registry/$dockerhub_repository:$image_tag
             docker run -it -d -p 5000:5000 $dockerhub_repository:$image_tag
             
      
