name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
           
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
           USERNAME: ${{ secrets.DOCKER_USERNAME }}
           PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Deploy  
      env: 
           dockerhub_registry: niskarsha10
           dockerhub_repository: github-image
           image_tag: ${{ github.sha }}
           
      run: |
           
             # docker build . --file Dockerfile --tag dockerimage12
             docker build -t $dockerhub_registry/$dockerhub_repository:$image_tag .
             docker push $dockerhub_registry/$dockerhub_repository:$image_tag
             docker-compose up -d
     
     
      #  name: Build and push
      #  uses: docker/build-push-action@v2
      #  with:
      #  push: true
      # tags: user/app:latest
